version: '3'

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=ipsdh#2023
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:443
    volumes:
      - nextcloud:/var/www/html:z
      - ./etc/ssl/nextcloud:/etc/ssl/nextcloud
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - TZ=Asia/Jakarta
      - PHP_UPLOAD_LIMIT=8G
      - PHP_MEMORY_LIMIT=8G
      - POST_MAX_SIZE=8G
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
