version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ipsdh#2023
      - MYSQL_PASSWORD=ipsdh#2023
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    # image: nextcloud:26.0
    build: .
    restart: always
    ports:
    # - 80:80
      - 443:443
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./etc/ssl/nextcloud:/etc/ssl/nextcloud 
    environment:
      - MYSQL_PASSWORD=ipsdh#2023
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PHP_MEMORY_LIMIT=4G
      - PHP_UPLOAD_LIMIT=4G
      
